package com.nt.exception;

import javax.management.IntrospectionException;

public class Test {
	
	
/*	try {
		int a;int b;
	int c=b+a;
	}catch(Exception e) {}
	*/
	public static void main(String[] args) /*throws InterruptedException*/{
		
		//for checked exception.
		/*try {
			throw new InterruptedException();
		}
		catch(InterruptedException ie) {}
		finally {}
	
		*/
		
		throw new ArithmeticException();
		
		
		
		
	}

}

